Repository canonical/saml-integrator-operator, pull requests merged in 2024-08, with the labels that each got.

#92 Fix link to charm configuration
  docs/how-to/configure-saml.md
Labels: documentation, Libraries: OK, trivial

#93 Fix decoding issues when metadata is not encoded in utf-8
  src/saml.py
  tests/unit/files/non_utf8_metadata_unsigned.xml
  tests/unit/test_saml.py
Labels: Libraries: OK, trivial

#95 Support configuring the metadata directly
  config.yaml
  lib/charms/saml_integrator/v0/saml.py
  src/charm_state.py
  src/saml.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_saml.py
Labels: Libraries: Out of sync, complex

#94 Install the same set of packages on install or charm upgrade
  .gitignore
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: OK, trivial

#96 Ensure correct packages are always installed
  src/charm.py
  tests/unit/test_charm.py
Labels: Libraries: OK, trivial

#81 Use statically linked dependencies
  charmcraft.yaml
  lib/charms/operator_libs_linux/v0/apt.py
  requirements-charmcraft.txt
  requirements-lxml.txt
  requirements.txt
  src/charm.py
  src/saml.py
  tests/interface/conftest.py
  tests/unit/test_charm.py
  tox.ini
Labels: Libraries: OK
